version: '3'

services:
  redis-forum:
    image: redis
    restart: unless-stopped
    expose:
      - 6379

  db-forum:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  api:
    build:
      context: .
    container_name: blog-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DB_HOST: db-forum
      REDIS_HOST: redis-forum
    depends_on:
      - db-forum
      - redis-forum
    command: bash -c "alembic upgrade head && uvicorn --host 0.0.0.0 app:app --reload"
