"""add relation

Revision ID: a1294fe56a1e
Revises: 3aa1d8792817
Create Date: 2022-10-27 20:12:44.880321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1294fe56a1e'
down_revision = '3aa1d8792817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
