"""add comments

Revision ID: f96a21e4a87a
Revises: a1294fe56a1e
Create Date: 2022-10-28 00:29:52.955238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96a21e4a87a'
down_revision = 'a1294fe56a1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('comments', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
